### ISSUE TITLE
Problems with version 9.5

### ISSUE THREAD

**Issue by fgomezotero** [petercelentanojr/timescaledb_collectd_resources#1]
Hello, 
What changes are necessary for it to work with a version 9.5 database?
Regards.

**Comment by petercelentanojr** [comment]
I haven't tested with version 9.5 recently, but some of the monitoring queries might be different (due to changes in pg_stat_activity compared to more recent versions).

Code wise, most of the monitoring queries should still work.  As long as TimescaleDB is installed and functioning properly, you should be good to go
